name: nativeflplug
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^9.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.nativeflplug
        pluginClass: NativeflplugPlugin
      ios:
        pluginClass: NativeflplugPlugin

ffigen:
  output: lib/src/nativefl.dart
  name: Nativefl
  description: Native bindings for nativefl
  headers:
    entry-points:
      - libnativeffi.h